version: 1.0.0.{build}

branches:
  except:
    - gh-pages

skip_tags: true

skip_commits:
  message: \[(ci skip|skip ci)\].*

clone_depth: 50

test: off

install:
  - ps: Install-Product node ''

build_script:
  - cmd: build.cmd

cache:
  - node_modules -> package.json
  - packages -> paket.lock
  - paket-files -> paket.lock
  - database\packages -> database\paket.lock
